/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A problem that indicates that the resource requested violates the precepts of this API.
type DisallowedResourceProblem struct {
	Type_ string `json:"type"`
	Title string `json:"title"`
	Detail string `json:"detail,omitempty"`
	Status int32 `json:"status,omitempty"`
	ResourceId string `json:"resource_id"`
	ResourceType string `json:"resource_type"`
	Section string `json:"section"`
}
