/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Expansions struct {
	Users []User `json:"users,omitempty"`
	Tweets []Tweet `json:"tweets,omitempty"`
	Places []Place `json:"places,omitempty"`
	Media []Media `json:"media,omitempty"`
	Polls []Poll `json:"polls,omitempty"`
}
