/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A response from modifying user-specified stream filtering rules.
type AddOrDeleteRulesResponse struct {
	// All user-specified stream filtering rules that were created.
	Data []Rule `json:"data,omitempty"`
	Meta *RulesResponseMetadata `json:"meta"`
	Errors []Problem `json:"errors,omitempty"`
}
