/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// ContextAnnotationDomainFields Represents the data for the context annotation domain.
type ContextAnnotationDomainFields struct {
	// The unique id for a context annotation domain.
	Id string `json:"id"`
	// Name of the context annotation domain.
	Name *string `json:"name,omitempty"`
	// Description of the context annotation domain.
	Description *string `json:"description,omitempty"`
}

// NewContextAnnotationDomainFields instantiates a new ContextAnnotationDomainFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContextAnnotationDomainFields(id string) *ContextAnnotationDomainFields {
	this := ContextAnnotationDomainFields{}
	this.Id = id
	return &this
}

// NewContextAnnotationDomainFieldsWithDefaults instantiates a new ContextAnnotationDomainFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContextAnnotationDomainFieldsWithDefaults() *ContextAnnotationDomainFields {
	this := ContextAnnotationDomainFields{}
	return &this
}

// GetId returns the Id field value
func (o *ContextAnnotationDomainFields) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ContextAnnotationDomainFields) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContextAnnotationDomainFields) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContextAnnotationDomainFields) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextAnnotationDomainFields) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContextAnnotationDomainFields) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContextAnnotationDomainFields) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ContextAnnotationDomainFields) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContextAnnotationDomainFields) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ContextAnnotationDomainFields) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ContextAnnotationDomainFields) SetDescription(v string) {
	o.Description = &v
}

func (o ContextAnnotationDomainFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableContextAnnotationDomainFields struct {
	value *ContextAnnotationDomainFields
	isSet bool
}

func (v NullableContextAnnotationDomainFields) Get() *ContextAnnotationDomainFields {
	return v.value
}

func (v *NullableContextAnnotationDomainFields) Set(val *ContextAnnotationDomainFields) {
	v.value = val
	v.isSet = true
}

func (v NullableContextAnnotationDomainFields) IsSet() bool {
	return v.isSet
}

func (v *NullableContextAnnotationDomainFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContextAnnotationDomainFields(val *ContextAnnotationDomainFields) *NullableContextAnnotationDomainFields {
	return &NullableContextAnnotationDomainFields{value: val, isSet: true}
}

func (v NullableContextAnnotationDomainFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContextAnnotationDomainFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


