/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TweetSearchResponseMeta struct {
	// Most recent Tweet Id returned by search query
	NewestId string `json:"newest_id,omitempty"`
	// Oldest Tweet Id returned by search query
	OldestId string `json:"oldest_id,omitempty"`
	// This value is used to get the next 'page' of results by providing it to the next_token parameter.
	NextToken string `json:"next_token,omitempty"`
	// Number of search query results
	ResultCount int32 `json:"result_count,omitempty"`
}
