/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MultiComplianceJobResponseMeta struct {
	// Number of compliance jobs returned
	ResultCount int32 `json:"result_count,omitempty"`
}
