/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represent a Poll attached to a Tweet
type Poll struct {
	Id string `json:"id"`
	Options []PollOption `json:"options"`
	VotingStatus string `json:"voting_status,omitempty"`
	EndDatetime time.Time `json:"end_datetime,omitempty"`
	DurationMinutes int32 `json:"duration_minutes,omitempty"`
}
