/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Space struct {
	Id string `json:"id"`
	// The current state of the space.
	State string `json:"state"`
	// When the space was started as a date string
	StartedAt time.Time `json:"started_at,omitempty"`
	// Denotes if the space is a ticketed space
	IsTicketed bool `json:"is_ticketed,omitempty"`
	// The number of participants in a space
	ParticipantCount int32 `json:"participant_count,omitempty"`
	// The title of the space
	Title string `json:"title,omitempty"`
	// The user ids for the hosts of the space
	HostIds []string `json:"host_ids,omitempty"`
	// When the space was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Creation time of the space
	CreatedAt time.Time `json:"created_at,omitempty"`
	CreatorId string `json:"creator_id,omitempty"`
	// The language of the space
	Lang string `json:"lang,omitempty"`
	// An array of user ids for people who were speakers in a space
	SpeakerIds []string `json:"speaker_ids,omitempty"`
	// An array of user ids for people who were invited to a space
	InvitedUserIds []string `json:"invited_user_ids,omitempty"`
	// A date time stamp for when a space is scheduled to begin
	ScheduledStart time.Time `json:"scheduled_start,omitempty"`
	// End time of the space
	EndedAt time.Time `json:"ended_at,omitempty"`
	// The topics of a space, as selected by its creator
	Topics []SpaceTopics `json:"topics,omitempty"`
	// The number of people who have either purchased a ticket or set a reminder for this space.
	SubscriberCount int32 `json:"subscriber_count,omitempty"`
}
