/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FullTextEntities struct {
	Urls []UrlEntity `json:"urls,omitempty"`
	Hashtags []HashtagEntity `json:"hashtags,omitempty"`
	Mentions []MentionEntity `json:"mentions,omitempty"`
	Cashtags []CashtagEntity `json:"cashtags,omitempty"`
}
