/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// TweetLookupResponse struct for TweetLookupResponse
type TweetLookupResponse struct {
	Data []Tweet `json:"data,omitempty"`
	Includes *Expansions `json:"includes,omitempty"`
	Errors []Problem `json:"errors,omitempty"`
}

// NewTweetLookupResponse instantiates a new TweetLookupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetLookupResponse() *TweetLookupResponse {
	this := TweetLookupResponse{}
	return &this
}

// NewTweetLookupResponseWithDefaults instantiates a new TweetLookupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetLookupResponseWithDefaults() *TweetLookupResponse {
	this := TweetLookupResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TweetLookupResponse) GetData() []Tweet {
	if o == nil || o.Data == nil {
		var ret []Tweet
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetLookupResponse) GetDataOk() ([]Tweet, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TweetLookupResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Tweet and assigns it to the Data field.
func (o *TweetLookupResponse) SetData(v []Tweet) {
	o.Data = v
}

// GetIncludes returns the Includes field value if set, zero value otherwise.
func (o *TweetLookupResponse) GetIncludes() Expansions {
	if o == nil || o.Includes == nil {
		var ret Expansions
		return ret
	}
	return *o.Includes
}

// GetIncludesOk returns a tuple with the Includes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetLookupResponse) GetIncludesOk() (*Expansions, bool) {
	if o == nil || o.Includes == nil {
		return nil, false
	}
	return o.Includes, true
}

// HasIncludes returns a boolean if a field has been set.
func (o *TweetLookupResponse) HasIncludes() bool {
	if o != nil && o.Includes != nil {
		return true
	}

	return false
}

// SetIncludes gets a reference to the given Expansions and assigns it to the Includes field.
func (o *TweetLookupResponse) SetIncludes(v Expansions) {
	o.Includes = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *TweetLookupResponse) GetErrors() []Problem {
	if o == nil || o.Errors == nil {
		var ret []Problem
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetLookupResponse) GetErrorsOk() ([]Problem, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *TweetLookupResponse) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Problem and assigns it to the Errors field.
func (o *TweetLookupResponse) SetErrors(v []Problem) {
	o.Errors = v
}

func (o TweetLookupResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Includes != nil {
		toSerialize["includes"] = o.Includes
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableTweetLookupResponse struct {
	value *TweetLookupResponse
	isSet bool
}

func (v NullableTweetLookupResponse) Get() *TweetLookupResponse {
	return v.value
}

func (v *NullableTweetLookupResponse) Set(val *TweetLookupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetLookupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetLookupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetLookupResponse(val *TweetLookupResponse) *NullableTweetLookupResponse {
	return &NullableTweetLookupResponse{value: val, isSet: true}
}

func (v NullableTweetLookupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetLookupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


