/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListUpdateRequest struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Private bool `json:"private,omitempty"`
}
