/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QuoteTweetLookupResponseMeta struct {
	// This value is used to get the next 'page' of results by providing it to the pagination_token parameter.
	NextToken string `json:"next_token,omitempty"`
	// The number of quoting tweets returned in this response
	ResultCount int32 `json:"result_count,omitempty"`
}
