/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// Video struct for Video
type Video struct {
	Type *string `json:"type,omitempty"`
	PreviewImageUrl *string `json:"preview_image_url,omitempty"`
	DurationMs *int32 `json:"duration_ms,omitempty"`
	// Engagement metrics for the Media at the time of the request.
	PublicMetrics *map[string]interface{} `json:"public_metrics,omitempty"`
	// Nonpublic engagement metrics for the Media at the time of the request.
	NonPublicMetrics *map[string]interface{} `json:"non_public_metrics,omitempty"`
	// Organic nonpublic engagement metrics for the Media at the time of the request.
	OrganicMetrics *map[string]interface{} `json:"organic_metrics,omitempty"`
	// Promoted nonpublic engagement metrics for the Media at the time of the request.
	PromotedMetrics *map[string]interface{} `json:"promoted_metrics,omitempty"`
	// The Media Key identifier for this attachment.
	MediaKey *string `json:"media_key,omitempty"`
	// The height of the media in pixels
	Height *int32 `json:"height,omitempty"`
	// The width of the media in pixels
	Width *int32 `json:"width,omitempty"`
}

// NewVideo instantiates a new Video object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideo() *Video {
	this := Video{}
	return &this
}

// NewVideoWithDefaults instantiates a new Video object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoWithDefaults() *Video {
	this := Video{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Video) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Video) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Video) SetType(v string) {
	o.Type = &v
}

// GetPreviewImageUrl returns the PreviewImageUrl field value if set, zero value otherwise.
func (o *Video) GetPreviewImageUrl() string {
	if o == nil || o.PreviewImageUrl == nil {
		var ret string
		return ret
	}
	return *o.PreviewImageUrl
}

// GetPreviewImageUrlOk returns a tuple with the PreviewImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetPreviewImageUrlOk() (*string, bool) {
	if o == nil || o.PreviewImageUrl == nil {
		return nil, false
	}
	return o.PreviewImageUrl, true
}

// HasPreviewImageUrl returns a boolean if a field has been set.
func (o *Video) HasPreviewImageUrl() bool {
	if o != nil && o.PreviewImageUrl != nil {
		return true
	}

	return false
}

// SetPreviewImageUrl gets a reference to the given string and assigns it to the PreviewImageUrl field.
func (o *Video) SetPreviewImageUrl(v string) {
	o.PreviewImageUrl = &v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *Video) GetDurationMs() int32 {
	if o == nil || o.DurationMs == nil {
		var ret int32
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetDurationMsOk() (*int32, bool) {
	if o == nil || o.DurationMs == nil {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *Video) HasDurationMs() bool {
	if o != nil && o.DurationMs != nil {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given int32 and assigns it to the DurationMs field.
func (o *Video) SetDurationMs(v int32) {
	o.DurationMs = &v
}

// GetPublicMetrics returns the PublicMetrics field value if set, zero value otherwise.
func (o *Video) GetPublicMetrics() map[string]interface{} {
	if o == nil || o.PublicMetrics == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.PublicMetrics
}

// GetPublicMetricsOk returns a tuple with the PublicMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetPublicMetricsOk() (*map[string]interface{}, bool) {
	if o == nil || o.PublicMetrics == nil {
		return nil, false
	}
	return o.PublicMetrics, true
}

// HasPublicMetrics returns a boolean if a field has been set.
func (o *Video) HasPublicMetrics() bool {
	if o != nil && o.PublicMetrics != nil {
		return true
	}

	return false
}

// SetPublicMetrics gets a reference to the given map[string]interface{} and assigns it to the PublicMetrics field.
func (o *Video) SetPublicMetrics(v map[string]interface{}) {
	o.PublicMetrics = &v
}

// GetNonPublicMetrics returns the NonPublicMetrics field value if set, zero value otherwise.
func (o *Video) GetNonPublicMetrics() map[string]interface{} {
	if o == nil || o.NonPublicMetrics == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.NonPublicMetrics
}

// GetNonPublicMetricsOk returns a tuple with the NonPublicMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetNonPublicMetricsOk() (*map[string]interface{}, bool) {
	if o == nil || o.NonPublicMetrics == nil {
		return nil, false
	}
	return o.NonPublicMetrics, true
}

// HasNonPublicMetrics returns a boolean if a field has been set.
func (o *Video) HasNonPublicMetrics() bool {
	if o != nil && o.NonPublicMetrics != nil {
		return true
	}

	return false
}

// SetNonPublicMetrics gets a reference to the given map[string]interface{} and assigns it to the NonPublicMetrics field.
func (o *Video) SetNonPublicMetrics(v map[string]interface{}) {
	o.NonPublicMetrics = &v
}

// GetOrganicMetrics returns the OrganicMetrics field value if set, zero value otherwise.
func (o *Video) GetOrganicMetrics() map[string]interface{} {
	if o == nil || o.OrganicMetrics == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.OrganicMetrics
}

// GetOrganicMetricsOk returns a tuple with the OrganicMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetOrganicMetricsOk() (*map[string]interface{}, bool) {
	if o == nil || o.OrganicMetrics == nil {
		return nil, false
	}
	return o.OrganicMetrics, true
}

// HasOrganicMetrics returns a boolean if a field has been set.
func (o *Video) HasOrganicMetrics() bool {
	if o != nil && o.OrganicMetrics != nil {
		return true
	}

	return false
}

// SetOrganicMetrics gets a reference to the given map[string]interface{} and assigns it to the OrganicMetrics field.
func (o *Video) SetOrganicMetrics(v map[string]interface{}) {
	o.OrganicMetrics = &v
}

// GetPromotedMetrics returns the PromotedMetrics field value if set, zero value otherwise.
func (o *Video) GetPromotedMetrics() map[string]interface{} {
	if o == nil || o.PromotedMetrics == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.PromotedMetrics
}

// GetPromotedMetricsOk returns a tuple with the PromotedMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetPromotedMetricsOk() (*map[string]interface{}, bool) {
	if o == nil || o.PromotedMetrics == nil {
		return nil, false
	}
	return o.PromotedMetrics, true
}

// HasPromotedMetrics returns a boolean if a field has been set.
func (o *Video) HasPromotedMetrics() bool {
	if o != nil && o.PromotedMetrics != nil {
		return true
	}

	return false
}

// SetPromotedMetrics gets a reference to the given map[string]interface{} and assigns it to the PromotedMetrics field.
func (o *Video) SetPromotedMetrics(v map[string]interface{}) {
	o.PromotedMetrics = &v
}

// GetMediaKey returns the MediaKey field value if set, zero value otherwise.
func (o *Video) GetMediaKey() string {
	if o == nil || o.MediaKey == nil {
		var ret string
		return ret
	}
	return *o.MediaKey
}

// GetMediaKeyOk returns a tuple with the MediaKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetMediaKeyOk() (*string, bool) {
	if o == nil || o.MediaKey == nil {
		return nil, false
	}
	return o.MediaKey, true
}

// HasMediaKey returns a boolean if a field has been set.
func (o *Video) HasMediaKey() bool {
	if o != nil && o.MediaKey != nil {
		return true
	}

	return false
}

// SetMediaKey gets a reference to the given string and assigns it to the MediaKey field.
func (o *Video) SetMediaKey(v string) {
	o.MediaKey = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Video) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Video) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *Video) SetHeight(v int32) {
	o.Height = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Video) GetWidth() int32 {
	if o == nil || o.Width == nil {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Video) GetWidthOk() (*int32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Video) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *Video) SetWidth(v int32) {
	o.Width = &v
}

func (o Video) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.PreviewImageUrl != nil {
		toSerialize["preview_image_url"] = o.PreviewImageUrl
	}
	if o.DurationMs != nil {
		toSerialize["duration_ms"] = o.DurationMs
	}
	if o.PublicMetrics != nil {
		toSerialize["public_metrics"] = o.PublicMetrics
	}
	if o.NonPublicMetrics != nil {
		toSerialize["non_public_metrics"] = o.NonPublicMetrics
	}
	if o.OrganicMetrics != nil {
		toSerialize["organic_metrics"] = o.OrganicMetrics
	}
	if o.PromotedMetrics != nil {
		toSerialize["promoted_metrics"] = o.PromotedMetrics
	}
	if o.MediaKey != nil {
		toSerialize["media_key"] = o.MediaKey
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.Width != nil {
		toSerialize["width"] = o.Width
	}
	return json.Marshal(toSerialize)
}

type NullableVideo struct {
	value *Video
	isSet bool
}

func (v NullableVideo) Get() *Video {
	return v.value
}

func (v *NullableVideo) Set(val *Video) {
	v.value = val
	v.isSet = true
}

func (v NullableVideo) IsSet() bool {
	return v.isSet
}

func (v *NullableVideo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideo(val *Video) *NullableVideo {
	return &NullableVideo{value: val, isSet: true}
}

func (v NullableVideo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


