/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MultiTweetLookupResponseMeta struct {
	// The number of spaces results returned in this response
	ResultCount int32 `json:"result_count,omitempty"`
}
