/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// UnsupportedAuthenticationProblem A problem that indicates that the authentication used is not supported.
type UnsupportedAuthenticationProblem struct {
	Type *string `json:"type,omitempty"`
	Title string `json:"title"`
	Detail string `json:"detail"`
}

// NewUnsupportedAuthenticationProblem instantiates a new UnsupportedAuthenticationProblem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnsupportedAuthenticationProblem(type_ string, title string, detail string) *UnsupportedAuthenticationProblem {
	this := UnsupportedAuthenticationProblem{}
	this.Type = &type_
	this.Title = title
	this.Detail = detail
	return &this
}

// NewUnsupportedAuthenticationProblemWithDefaults instantiates a new UnsupportedAuthenticationProblem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnsupportedAuthenticationProblemWithDefaults() *UnsupportedAuthenticationProblem {
	this := UnsupportedAuthenticationProblem{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UnsupportedAuthenticationProblem) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsupportedAuthenticationProblem) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UnsupportedAuthenticationProblem) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UnsupportedAuthenticationProblem) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value
func (o *UnsupportedAuthenticationProblem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *UnsupportedAuthenticationProblem) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UnsupportedAuthenticationProblem) SetTitle(v string) {
	o.Title = v
}

// GetDetail returns the Detail field value
func (o *UnsupportedAuthenticationProblem) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *UnsupportedAuthenticationProblem) GetDetailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *UnsupportedAuthenticationProblem) SetDetail(v string) {
	o.Detail = v
}

func (o UnsupportedAuthenticationProblem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["detail"] = o.Detail
	}
	return json.Marshal(toSerialize)
}

type NullableUnsupportedAuthenticationProblem struct {
	value *UnsupportedAuthenticationProblem
	isSet bool
}

func (v NullableUnsupportedAuthenticationProblem) Get() *UnsupportedAuthenticationProblem {
	return v.value
}

func (v *NullableUnsupportedAuthenticationProblem) Set(val *UnsupportedAuthenticationProblem) {
	v.value = val
	v.isSet = true
}

func (v NullableUnsupportedAuthenticationProblem) IsSet() bool {
	return v.isSet
}

func (v *NullableUnsupportedAuthenticationProblem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnsupportedAuthenticationProblem(val *UnsupportedAuthenticationProblem) *NullableUnsupportedAuthenticationProblem {
	return &NullableUnsupportedAuthenticationProblem{value: val, isSet: true}
}

func (v NullableUnsupportedAuthenticationProblem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnsupportedAuthenticationProblem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


