/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// TweetNonPublicMetrics Nonpublic engagement metrics for the Tweet at the time of the request.
type TweetNonPublicMetrics struct {
	// Number of times this Tweet has been viewed.
	ImpressionCount *int32 `json:"impression_count,omitempty"`
	// Number of times the user's profile from this Tweet has been clicked.
	UserProfileClicks *int32 `json:"user_profile_clicks,omitempty"`
	// Number of times links in this Tweet have been clicked.
	UrlLinkClicks *int32 `json:"url_link_clicks,omitempty"`
}

// NewTweetNonPublicMetrics instantiates a new TweetNonPublicMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetNonPublicMetrics() *TweetNonPublicMetrics {
	this := TweetNonPublicMetrics{}
	return &this
}

// NewTweetNonPublicMetricsWithDefaults instantiates a new TweetNonPublicMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetNonPublicMetricsWithDefaults() *TweetNonPublicMetrics {
	this := TweetNonPublicMetrics{}
	return &this
}

// GetImpressionCount returns the ImpressionCount field value if set, zero value otherwise.
func (o *TweetNonPublicMetrics) GetImpressionCount() int32 {
	if o == nil || o.ImpressionCount == nil {
		var ret int32
		return ret
	}
	return *o.ImpressionCount
}

// GetImpressionCountOk returns a tuple with the ImpressionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetNonPublicMetrics) GetImpressionCountOk() (*int32, bool) {
	if o == nil || o.ImpressionCount == nil {
		return nil, false
	}
	return o.ImpressionCount, true
}

// HasImpressionCount returns a boolean if a field has been set.
func (o *TweetNonPublicMetrics) HasImpressionCount() bool {
	if o != nil && o.ImpressionCount != nil {
		return true
	}

	return false
}

// SetImpressionCount gets a reference to the given int32 and assigns it to the ImpressionCount field.
func (o *TweetNonPublicMetrics) SetImpressionCount(v int32) {
	o.ImpressionCount = &v
}

// GetUserProfileClicks returns the UserProfileClicks field value if set, zero value otherwise.
func (o *TweetNonPublicMetrics) GetUserProfileClicks() int32 {
	if o == nil || o.UserProfileClicks == nil {
		var ret int32
		return ret
	}
	return *o.UserProfileClicks
}

// GetUserProfileClicksOk returns a tuple with the UserProfileClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetNonPublicMetrics) GetUserProfileClicksOk() (*int32, bool) {
	if o == nil || o.UserProfileClicks == nil {
		return nil, false
	}
	return o.UserProfileClicks, true
}

// HasUserProfileClicks returns a boolean if a field has been set.
func (o *TweetNonPublicMetrics) HasUserProfileClicks() bool {
	if o != nil && o.UserProfileClicks != nil {
		return true
	}

	return false
}

// SetUserProfileClicks gets a reference to the given int32 and assigns it to the UserProfileClicks field.
func (o *TweetNonPublicMetrics) SetUserProfileClicks(v int32) {
	o.UserProfileClicks = &v
}

// GetUrlLinkClicks returns the UrlLinkClicks field value if set, zero value otherwise.
func (o *TweetNonPublicMetrics) GetUrlLinkClicks() int32 {
	if o == nil || o.UrlLinkClicks == nil {
		var ret int32
		return ret
	}
	return *o.UrlLinkClicks
}

// GetUrlLinkClicksOk returns a tuple with the UrlLinkClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetNonPublicMetrics) GetUrlLinkClicksOk() (*int32, bool) {
	if o == nil || o.UrlLinkClicks == nil {
		return nil, false
	}
	return o.UrlLinkClicks, true
}

// HasUrlLinkClicks returns a boolean if a field has been set.
func (o *TweetNonPublicMetrics) HasUrlLinkClicks() bool {
	if o != nil && o.UrlLinkClicks != nil {
		return true
	}

	return false
}

// SetUrlLinkClicks gets a reference to the given int32 and assigns it to the UrlLinkClicks field.
func (o *TweetNonPublicMetrics) SetUrlLinkClicks(v int32) {
	o.UrlLinkClicks = &v
}

func (o TweetNonPublicMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ImpressionCount != nil {
		toSerialize["impression_count"] = o.ImpressionCount
	}
	if o.UserProfileClicks != nil {
		toSerialize["user_profile_clicks"] = o.UserProfileClicks
	}
	if o.UrlLinkClicks != nil {
		toSerialize["url_link_clicks"] = o.UrlLinkClicks
	}
	return json.Marshal(toSerialize)
}

type NullableTweetNonPublicMetrics struct {
	value *TweetNonPublicMetrics
	isSet bool
}

func (v NullableTweetNonPublicMetrics) Get() *TweetNonPublicMetrics {
	return v.value
}

func (v *NullableTweetNonPublicMetrics) Set(val *TweetNonPublicMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetNonPublicMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetNonPublicMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetNonPublicMetrics(val *TweetNonPublicMetrics) *NullableTweetNonPublicMetrics {
	return &NullableTweetNonPublicMetrics{value: val, isSet: true}
}

func (v NullableTweetNonPublicMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetNonPublicMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


