/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A list of metadata found in the user's profile description.
type UserEntities struct {
	Url *UserEntitiesUrl `json:"url,omitempty"`
	Description *FullTextEntities `json:"description,omitempty"`
}
