/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// TweetWithheld Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
type TweetWithheld struct {
	// Indicates if the content is being withheld for on the basis of copyright infringement.
	Copyright bool `json:"copyright"`
	// Provides a list of countries where this content is not available.
	CountryCodes []string `json:"country_codes"`
	// Indicates whether the content being withheld is the `tweet` or a `user`.
	Scope *string `json:"scope,omitempty"`
}

// NewTweetWithheld instantiates a new TweetWithheld object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetWithheld(copyright bool, countryCodes []string) *TweetWithheld {
	this := TweetWithheld{}
	this.Copyright = copyright
	this.CountryCodes = countryCodes
	return &this
}

// NewTweetWithheldWithDefaults instantiates a new TweetWithheld object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetWithheldWithDefaults() *TweetWithheld {
	this := TweetWithheld{}
	return &this
}

// GetCopyright returns the Copyright field value
func (o *TweetWithheld) GetCopyright() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Copyright
}

// GetCopyrightOk returns a tuple with the Copyright field value
// and a boolean to check if the value has been set.
func (o *TweetWithheld) GetCopyrightOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Copyright, true
}

// SetCopyright sets field value
func (o *TweetWithheld) SetCopyright(v bool) {
	o.Copyright = v
}

// GetCountryCodes returns the CountryCodes field value
func (o *TweetWithheld) GetCountryCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CountryCodes
}

// GetCountryCodesOk returns a tuple with the CountryCodes field value
// and a boolean to check if the value has been set.
func (o *TweetWithheld) GetCountryCodesOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CountryCodes, true
}

// SetCountryCodes sets field value
func (o *TweetWithheld) SetCountryCodes(v []string) {
	o.CountryCodes = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *TweetWithheld) GetScope() string {
	if o == nil || o.Scope == nil {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetWithheld) GetScopeOk() (*string, bool) {
	if o == nil || o.Scope == nil {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *TweetWithheld) HasScope() bool {
	if o != nil && o.Scope != nil {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *TweetWithheld) SetScope(v string) {
	o.Scope = &v
}

func (o TweetWithheld) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["copyright"] = o.Copyright
	}
	if true {
		toSerialize["country_codes"] = o.CountryCodes
	}
	if o.Scope != nil {
		toSerialize["scope"] = o.Scope
	}
	return json.Marshal(toSerialize)
}

type NullableTweetWithheld struct {
	value *TweetWithheld
	isSet bool
}

func (v NullableTweetWithheld) Get() *TweetWithheld {
	return v.value
}

func (v *NullableTweetWithheld) Set(val *TweetWithheld) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetWithheld) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetWithheld) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetWithheld(val *TweetWithheld) *NullableTweetWithheld {
	return &NullableTweetWithheld{value: val, isSet: true}
}

func (v NullableTweetWithheld) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetWithheld) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


