/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// CashtagFields Represent the portion of text recognized as a Cashtag, and its start and end position within the text.
type CashtagFields struct {
	Tag string `json:"tag"`
}

// NewCashtagFields instantiates a new CashtagFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCashtagFields(tag string) *CashtagFields {
	this := CashtagFields{}
	this.Tag = tag
	return &this
}

// NewCashtagFieldsWithDefaults instantiates a new CashtagFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCashtagFieldsWithDefaults() *CashtagFields {
	this := CashtagFields{}
	return &this
}

// GetTag returns the Tag field value
func (o *CashtagFields) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *CashtagFields) GetTagOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *CashtagFields) SetTag(v string) {
	o.Tag = v
}

func (o CashtagFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableCashtagFields struct {
	value *CashtagFields
	isSet bool
}

func (v NullableCashtagFields) Get() *CashtagFields {
	return v.value
}

func (v *NullableCashtagFields) Set(val *CashtagFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCashtagFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCashtagFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCashtagFields(val *CashtagFields) *NullableCashtagFields {
	return &NullableCashtagFields{value: val, isSet: true}
}

func (v NullableCashtagFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCashtagFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


