/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HashtagEntity struct {
	// The text of the Hashtag
	Tag string `json:"tag"`
	// Index (zero-based) at which position this entity starts.  The index is inclusive.
	Start int32 `json:"start"`
	// Index (zero-based) at which position this entity ends.  The index is exclusive.
	End int32 `json:"end"`
}
