/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InvalidRequestProblemErrors struct {
	Parameters map[string][]string `json:"parameters,omitempty"`
	Message string `json:"message,omitempty"`
}
