/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Tweet information of the Tweet being replied to.
type Model2tweetsReply struct {
	InReplyToTweetId string `json:"in_reply_to_tweet_id,omitempty"`
	// A list of User Ids to be excluded from the reply Tweet.
	ExcludeReplyUserIds []string `json:"exclude_reply_user_ids,omitempty"`
}
