/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// CashtagEntity struct for CashtagEntity
type CashtagEntity struct {
	// Index (zero-based) at which position this entity starts.
	Start int32 `json:"start"`
	// Index (zero-based) at which position this entity ends.
	End int32 `json:"end"`
	Tag string `json:"tag"`
}

// NewCashtagEntity instantiates a new CashtagEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCashtagEntity(start int32, end int32, tag string) *CashtagEntity {
	this := CashtagEntity{}
	this.Start = start
	this.End = end
	this.Tag = tag
	return &this
}

// NewCashtagEntityWithDefaults instantiates a new CashtagEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCashtagEntityWithDefaults() *CashtagEntity {
	this := CashtagEntity{}
	return &this
}

// GetStart returns the Start field value
func (o *CashtagEntity) GetStart() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *CashtagEntity) GetStartOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *CashtagEntity) SetStart(v int32) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *CashtagEntity) GetEnd() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *CashtagEntity) GetEndOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *CashtagEntity) SetEnd(v int32) {
	o.End = v
}

// GetTag returns the Tag field value
func (o *CashtagEntity) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *CashtagEntity) GetTagOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *CashtagEntity) SetTag(v string) {
	o.Tag = v
}

func (o CashtagEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["start"] = o.Start
	}
	if true {
		toSerialize["end"] = o.End
	}
	if true {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableCashtagEntity struct {
	value *CashtagEntity
	isSet bool
}

func (v NullableCashtagEntity) Get() *CashtagEntity {
	return v.value
}

func (v *NullableCashtagEntity) Set(val *CashtagEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableCashtagEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableCashtagEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCashtagEntity(val *CashtagEntity) *NullableCashtagEntity {
	return &NullableCashtagEntity{value: val, isSet: true}
}

func (v NullableCashtagEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCashtagEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


