/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A user-provided stream filtering rule.
type Rule struct {
	Value string `json:"value"`
	Tag string `json:"tag,omitempty"`
	Id string `json:"id,omitempty"`
}
