/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// CommonMediaFields This contains the list of the fields that are common to all media returned.
type CommonMediaFields struct {
	// The Media Key identifier for this attachment.
	MediaKey *string `json:"media_key,omitempty"`
	// The height of the media in pixels
	Height *int32 `json:"height,omitempty"`
	// The width of the media in pixels
	Width *int32 `json:"width,omitempty"`
}

// NewCommonMediaFields instantiates a new CommonMediaFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonMediaFields() *CommonMediaFields {
	this := CommonMediaFields{}
	return &this
}

// NewCommonMediaFieldsWithDefaults instantiates a new CommonMediaFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonMediaFieldsWithDefaults() *CommonMediaFields {
	this := CommonMediaFields{}
	return &this
}

// GetMediaKey returns the MediaKey field value if set, zero value otherwise.
func (o *CommonMediaFields) GetMediaKey() string {
	if o == nil || o.MediaKey == nil {
		var ret string
		return ret
	}
	return *o.MediaKey
}

// GetMediaKeyOk returns a tuple with the MediaKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonMediaFields) GetMediaKeyOk() (*string, bool) {
	if o == nil || o.MediaKey == nil {
		return nil, false
	}
	return o.MediaKey, true
}

// HasMediaKey returns a boolean if a field has been set.
func (o *CommonMediaFields) HasMediaKey() bool {
	if o != nil && o.MediaKey != nil {
		return true
	}

	return false
}

// SetMediaKey gets a reference to the given string and assigns it to the MediaKey field.
func (o *CommonMediaFields) SetMediaKey(v string) {
	o.MediaKey = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *CommonMediaFields) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonMediaFields) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *CommonMediaFields) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *CommonMediaFields) SetHeight(v int32) {
	o.Height = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *CommonMediaFields) GetWidth() int32 {
	if o == nil || o.Width == nil {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonMediaFields) GetWidthOk() (*int32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *CommonMediaFields) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *CommonMediaFields) SetWidth(v int32) {
	o.Width = &v
}

func (o CommonMediaFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MediaKey != nil {
		toSerialize["media_key"] = o.MediaKey
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.Width != nil {
		toSerialize["width"] = o.Width
	}
	return json.Marshal(toSerialize)
}

type NullableCommonMediaFields struct {
	value *CommonMediaFields
	isSet bool
}

func (v NullableCommonMediaFields) Get() *CommonMediaFields {
	return v.value
}

func (v *NullableCommonMediaFields) Set(val *CommonMediaFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonMediaFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonMediaFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonMediaFields(val *CommonMediaFields) *NullableCommonMediaFields {
	return &NullableCommonMediaFields{value: val, isSet: true}
}

func (v NullableCommonMediaFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonMediaFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


