/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to create a new batch compliance job.
type ComplianceJobsBody struct {
	Type_ *ComplianceJobType `json:"type"`
	// If true, this endpoint will return a pre-signed URL with resumable uploads enabled
	Resumable bool `json:"resumable,omitempty"`
	Name string `json:"name,omitempty"`
}
