/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MultiListNoPaginationResponse struct {
	Data []List `json:"data,omitempty"`
	Meta *MultiListNoPaginationResponseMeta `json:"meta,omitempty"`
	Errors []Problem `json:"errors,omitempty"`
}
