/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Poll options for a Tweet with a poll. This is mutually exclusive from Media and Quote Tweet Id.
type Model2tweetsPoll struct {
	Options []string `json:"options,omitempty"`
	DurationMinutes int32 `json:"duration_minutes,omitempty"`
}
