/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// HashtagFields Represent the portion of text recognized as a Hashtag, and its start and end position within the text.
type HashtagFields struct {
	// The text of the Hashtag
	Tag string `json:"tag"`
}

// NewHashtagFields instantiates a new HashtagFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHashtagFields(tag string) *HashtagFields {
	this := HashtagFields{}
	this.Tag = tag
	return &this
}

// NewHashtagFieldsWithDefaults instantiates a new HashtagFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHashtagFieldsWithDefaults() *HashtagFields {
	this := HashtagFields{}
	return &this
}

// GetTag returns the Tag field value
func (o *HashtagFields) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *HashtagFields) GetTagOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *HashtagFields) SetTag(v string) {
	o.Tag = v
}

func (o HashtagFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableHashtagFields struct {
	value *HashtagFields
	isSet bool
}

func (v NullableHashtagFields) Get() *HashtagFields {
	return v.value
}

func (v *NullableHashtagFields) Set(val *HashtagFields) {
	v.value = val
	v.isSet = true
}

func (v NullableHashtagFields) IsSet() bool {
	return v.isSet
}

func (v *NullableHashtagFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHashtagFields(val *HashtagFields) *NullableHashtagFields {
	return &NullableHashtagFields{value: val, isSet: true}
}

func (v NullableHashtagFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHashtagFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


