/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Annotation inferred from the tweet text.
type ContextAnnotation struct {
	Domain *ContextAnnotationDomainFields `json:"domain"`
	Entity *ContextAnnotationEntityFields `json:"entity"`
}
