/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represent the portion of text recognized as a User mention, and its start and end position within the text.
type MentionFields struct {
	Username string `json:"username"`
	Id string `json:"id"`
}
