/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FilteredStreamingTweetMatchingRules struct {
	Id string `json:"id"`
	// The user-supplied tag assigned to the rule which matched
	Tag string `json:"tag,omitempty"`
}
