/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ComplianceJob struct {
	Id string `json:"id"`
	Type_ *ComplianceJobType `json:"type"`
	CreatedAt *time.Time `json:"created_at"`
	UploadUrl string `json:"upload_url"`
	UploadExpiresAt *time.Time `json:"upload_expires_at"`
	DownloadUrl string `json:"download_url"`
	DownloadExpiresAt *time.Time `json:"download_expires_at"`
	Name string `json:"name,omitempty"`
	Status *ComplianceJobStatus `json:"status"`
}
