/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Photo struct {
	Type_ string `json:"type"`
	MediaKey string `json:"media_key,omitempty"`
	Height int32 `json:"height,omitempty"`
	Width int32 `json:"width,omitempty"`
	Url string `json:"url,omitempty"`
	AltText string `json:"alt_text,omitempty"`
}
