/*
Tweets and Users

API Reference — Labs v2

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package twitterapi

import (
	"encoding/json"
)

// ResourceUnauthorizedProblem A problem that indicates you are not allowed to see a particular Tweet, User, etc.
type ResourceUnauthorizedProblem struct {
	Type *string `json:"type,omitempty"`
	ResourceId string `json:"resource_id"`
	ResourceType string `json:"resource_type"`
	Section string `json:"section"`
	Title string `json:"title"`
	Detail string `json:"detail"`
}

// NewResourceUnauthorizedProblem instantiates a new ResourceUnauthorizedProblem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceUnauthorizedProblem(resourceId string, resourceType string, section string, type_ string, title string, detail string) *ResourceUnauthorizedProblem {
	this := ResourceUnauthorizedProblem{}
	this.Type = &type_
	this.Title = title
	this.Detail = detail
	return &this
}

// NewResourceUnauthorizedProblemWithDefaults instantiates a new ResourceUnauthorizedProblem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceUnauthorizedProblemWithDefaults() *ResourceUnauthorizedProblem {
	this := ResourceUnauthorizedProblem{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ResourceUnauthorizedProblem) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceUnauthorizedProblem) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ResourceUnauthorizedProblem) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ResourceUnauthorizedProblem) SetType(v string) {
	o.Type = &v
}

// GetResourceId returns the ResourceId field value
func (o *ResourceUnauthorizedProblem) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ResourceUnauthorizedProblem) GetResourceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ResourceUnauthorizedProblem) SetResourceId(v string) {
	o.ResourceId = v
}

// GetResourceType returns the ResourceType field value
func (o *ResourceUnauthorizedProblem) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ResourceUnauthorizedProblem) GetResourceTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ResourceUnauthorizedProblem) SetResourceType(v string) {
	o.ResourceType = v
}

// GetSection returns the Section field value
func (o *ResourceUnauthorizedProblem) GetSection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Section
}

// GetSectionOk returns a tuple with the Section field value
// and a boolean to check if the value has been set.
func (o *ResourceUnauthorizedProblem) GetSectionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Section, true
}

// SetSection sets field value
func (o *ResourceUnauthorizedProblem) SetSection(v string) {
	o.Section = v
}

// GetTitle returns the Title field value
func (o *ResourceUnauthorizedProblem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ResourceUnauthorizedProblem) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ResourceUnauthorizedProblem) SetTitle(v string) {
	o.Title = v
}

// GetDetail returns the Detail field value
func (o *ResourceUnauthorizedProblem) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *ResourceUnauthorizedProblem) GetDetailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *ResourceUnauthorizedProblem) SetDetail(v string) {
	o.Detail = v
}

func (o ResourceUnauthorizedProblem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["resource_id"] = o.ResourceId
	}
	if true {
		toSerialize["resource_type"] = o.ResourceType
	}
	if true {
		toSerialize["section"] = o.Section
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["detail"] = o.Detail
	}
	return json.Marshal(toSerialize)
}

type NullableResourceUnauthorizedProblem struct {
	value *ResourceUnauthorizedProblem
	isSet bool
}

func (v NullableResourceUnauthorizedProblem) Get() *ResourceUnauthorizedProblem {
	return v.value
}

func (v *NullableResourceUnauthorizedProblem) Set(val *ResourceUnauthorizedProblem) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceUnauthorizedProblem) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceUnauthorizedProblem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceUnauthorizedProblem(val *ResourceUnauthorizedProblem) *NullableResourceUnauthorizedProblem {
	return &NullableResourceUnauthorizedProblem{value: val, isSet: true}
}

func (v NullableResourceUnauthorizedProblem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceUnauthorizedProblem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


