/*
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * API version: 2.43
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GenericTweetsTimelineResponseMeta struct {
	NewestId string `json:"newest_id,omitempty"`
	OldestId string `json:"oldest_id,omitempty"`
	// The previous token
	PreviousToken string `json:"previous_token,omitempty"`
	// The next token
	NextToken string `json:"next_token,omitempty"`
	// Number of Tweets in result set
	ResultCount int32 `json:"result_count,omitempty"`
}
