openapi: 3.0.0
info:
  title: Twitter API v2
  description: Twitter API v2 available endpoints
  termsOfService: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  contact:
    name: Twitter Developers
    url: https://developer.twitter.com/
  license:
    name: Twitter Developer Agreement and Policy
    url: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  version: "2.43"
servers:
- url: https://api.twitter.com
  description: Twitter API
tags:
- name: Bookmarks
  description: "Endpoints related to retrieving, managing bookmarks of a user"
- name: Compliance
  description: Endpoints related to keeping Twitter data in your systems compliant
- name: General
  description: Miscellaneous endpoints for general API functionality
- name: Lists
  description: "Endpoints related to retrieving, managing Lists"
- name: Spaces
  description: "Endpoints related to retrieving, managing Spaces"
- name: Tweets
  description: "Endpoints related to retrieving, searching, and modifying Tweets"
- name: Users
  description: "Endpoints related to retrieving, managing relationships of Users"
paths:
  /2/users:
    get:
      tags:
      - Users
      summary: User lookup by IDs
      description: This endpoint returns information about users. Specify users by
        their ID.
      operationId: findUsersById
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/{id}:
    get:
      tags:
      - Users
      summary: User lookup by ID
      description: This endpoint returns information about a user. Specify user by
        ID.
      operationId: findUserById
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/by:
    get:
      tags:
      - Users
      summary: User lookup by usernames
      description: This endpoint returns information about users. Specify users by
        their username.
      operationId: findUsersByUsername
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/me:
    get:
      tags:
      - Users
      summary: User lookup me
      description: This endpoint returns information about the requesting user.
      operationId: findMyUser
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/by/username/{username}:
    get:
      tags:
      - Users
      summary: User lookup by username
      description: This endpoint returns information about a user. Specify user by
        username.
      operationId: findUserByUsername
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/{id}/blocking:
    get:
      tags:
      - Users
      summary: Returns user objects that are blocked by provided user ID
      description: Returns a list of users that are blocked by the provided user ID
      operationId: usersIdBlocking
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - block.read
    post:
      tags:
      - Users
      summary: Block User by User ID
      description: Causes the user (in the path) to block the target user. The user
        (in the path) must match the user context authorizing the request
      operationId: usersIdBlock
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - block.write
  /2/users/{source_user_id}/blocking/{target_user_id}:
    delete:
      tags:
      - Users
      summary: Unblock User by User ID
      description: Causes the source user to unblock the target user. The source user
        must match the user context authorizing the request
      operationId: usersIdUnblock
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - block.write
  /2/users/{id}/bookmarks:
    get:
      tags:
      - Bookmarks
      summary: Bookmarks by User
      description: Returns Tweet objects that have been bookmarked by the requesting
        user
      operationId: getUsersIdBookmarks
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - bookmark.read
    post:
      tags:
      - Bookmarks
      summary: Add Tweet to Bookmarks
      description: Adds a Tweet (ID in the body) to the requesting user's (in the
        path) bookmarks
      operationId: postUsersIdBookmarks
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - bookmark.write
  /2/users/{id}/bookmarks/{tweet_id}:
    delete:
      tags:
      - Bookmarks
      summary: Remove a bookmarked Tweet
      description: Removes a Tweet from the requesting user's bookmarked Tweets.
      operationId: usersIdBookmarksDelete
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - bookmark.write
  /2/users/{source_user_id}/muting/{target_user_id}:
    delete:
      tags:
      - Users
      summary: Unmute User by User ID
      description: Causes the source user to unmute the target user. The source user
        must match the user context authorizing the request
      operationId: usersIdUnmute
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - mute.write
  /2/users/{id}/muting:
    get:
      tags:
      - Users
      summary: Returns user objects that are muted by the provided user ID
      description: Returns a list of users that are muted by the provided user ID
      operationId: usersIdMuting
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - mute.read
    post:
      tags:
      - Users
      summary: Mute User by User ID
      description: Causes the user (in the path) to mute the target user. The user
        (in the path) must match the user context authorizing the request
      operationId: usersIdMute
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
        - mute.write
  /2/users/{id}/followers:
    get:
      tags:
      - Users
      summary: Returns user objects that follow the provided user ID
      description: Returns a list of users that follow the provided user ID
      operationId: usersIdFollowers
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - follows.read
  /2/users/{id}/following:
    get:
      tags:
      - Users
      summary: Following by User ID
      description: Returns a list of users that are being followed by the provided
        user ID
      operationId: usersIdFollowing
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - follows.read
    post:
      tags:
      - Users
      summary: Follow User
      description: "Causes the user(in the path) to follow, or “request to follow”\
        \ for protected users, the target user. The user(in the path) must match the\
        \ user context authorizing the request"
      operationId: usersIdFollow
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - follows.write
  /2/users/{source_user_id}/following/{target_user_id}:
    delete:
      tags:
      - Users
      summary: Unfollow User
      description: Causes the source user to unfollow the target user. The source
        user must match the user context authorizing the request
      operationId: usersIdUnfollow
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - follows.write
  /2/users/{id}/followed_lists:
    get:
      tags:
      - Lists
      summary: Get User's Followed Lists
      description: Returns a user's followed Lists.
      operationId: userFollowedLists
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
    post:
      tags:
      - Lists
      summary: Follow a List
      description: Causes a user to follow a List.
      operationId: listUserFollow
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/users/{id}/followed_lists/{list_id}:
    delete:
      tags:
      - Lists
      summary: Unfollow a List
      description: Causes a user to unfollow a List.
      operationId: listUserUnfollow
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/users/{id}/list_memberships:
    get:
      tags:
      - Lists
      summary: Get a User's List Memberships
      description: Get a User's List Memberships.
      operationId: getUserListMemberships
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
  /2/users/{id}/owned_lists:
    get:
      tags:
      - Lists
      summary: Get a User's Owned Lists
      description: Get a User's Owned Lists.
      operationId: listUserOwnedLists
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
  /2/users/{id}/pinned_lists:
    get:
      tags:
      - Lists
      summary: Get a User's Pinned Lists
      description: Get a User's Pinned Lists.
      operationId: listUserPinnedLists
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
    post:
      tags:
      - Lists
      summary: Pin a List
      description: Causes a user to pin a List.
      operationId: listUserPin
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/users/{id}/pinned_lists/{list_id}:
    delete:
      tags:
      - Lists
      summary: Unpin a List
      description: Causes a user to remove a pinned List.
      operationId: listUserUnpin
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/tweets:
    get:
      tags:
      - Tweets
      summary: Tweet lookup by Tweet IDs
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: findTweetsById
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
    post:
      tags:
      - Tweets
      summary: Creation of a Tweet
      description: Causes the user to create a tweet under the authorized account.
      operationId: createTweet
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - tweet.write
  /2/tweets/{id}:
    get:
      tags:
      - Tweets
      summary: Tweet lookup by Tweet ID
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: findTweetById
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
    delete:
      tags:
      - Tweets
      summary: Tweet delete by Tweet ID
      description: Delete specified Tweet (in the path) by ID.
      operationId: deleteTweetById
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - tweet.write
  /2/tweets/{id}/quote_tweets:
    get:
      tags:
      - Tweets
      summary: Retrieve tweets that quote a tweet.
      description: Returns a variety of information about each tweet that quotes the
        Tweet specified by the requested ID.
      operationId: findTweetsThatQuoteATweet
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/tweets/{id}/hidden:
    put:
      tags:
      - Tweets
      summary: Hide replies
      description: Hides or unhides a reply to an owned conversation.
      operationId: hideReplyById
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - tweet.moderate.write
  /2/tweets/search/recent:
    get:
      tags:
      - Tweets
      summary: Recent search
      description: Returns Tweets from the last 7 days that match a search query.
      operationId: tweetsRecentSearch
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/tweets/search/all:
    get:
      tags:
      - Tweets
      summary: Full-archive search
      description: Returns Tweets that match a search query.
      operationId: tweetsFullarchiveSearch
      security:
      - BearerToken: []
  /2/tweets/search/stream:
    get:
      tags:
      - Tweets
      summary: Filtered stream
      description: Streams Tweets matching the stream's active rule set.
      operationId: searchStream
      security:
      - BearerToken: []
      x-twitter-streaming: true
  /2/tweets/search/stream/rules:
    get:
      tags:
      - Tweets
      summary: Rules lookup
      description: "Returns rules from a user's active rule set. Users can fetch all\
        \ of their rules or a subset, specified by the provided rule ids."
      operationId: getRules
      security:
      - BearerToken: []
    post:
      tags:
      - Tweets
      summary: Add/Delete rules
      description: "Add or delete rules from a user's active rule set. Users can provide\
        \ unique, optionally tagged rules to add. Users can delete their entire rule\
        \ set or a subset specified by rule ids or values."
      operationId: addOrDeleteRules
      security:
      - BearerToken: []
  /2/tweets/sample/stream:
    get:
      tags:
      - Tweets
      summary: Sample stream
      description: Streams a deterministic 1% of public Tweets.
      operationId: sampleStream
      security:
      - BearerToken: []
      x-twitter-streaming: true
  /2/openapi.json:
    get:
      tags:
      - General
      summary: Returns the open api spec document.
      description: Full open api spec in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)
      operationId: getOpenApiSpec
  /2/users/{id}/timelines/reverse_chronological:
    get:
      tags:
      - Tweets
      summary: User home timeline by User ID
      description: Returns Tweet objects that appears in the provided User ID's home
        timeline
      operationId: usersIdTimeline
      security:
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/{id}/tweets:
    get:
      tags:
      - Tweets
      summary: User Tweets timeline by User ID
      description: Returns a list of Tweets authored by the provided User ID
      operationId: usersIdTweets
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/{id}/mentions:
    get:
      tags:
      - Tweets
      summary: User mention timeline by User ID
      description: Returns Tweet objects that mention username associated to the provided
        User ID
      operationId: usersIdMentions
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/{id}/likes:
    post:
      tags:
      - Tweets
      summary: Causes the user (in the path) to like the specified tweet
      description: Causes the user (in the path) to like the specified tweet. The
        user in the path must match the user context authorizing the request.
      operationId: usersIdLike
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - like.write
  /2/users/{id}/likes/{tweet_id}:
    delete:
      tags:
      - Tweets
      summary: Causes the user (in the path) to unlike the specified tweet
      description: Causes the user (in the path) to unlike the specified tweet. The
        user must match the user context authorizing the request
      operationId: usersIdUnlike
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - like.write
  /2/users/{id}/liked_tweets:
    get:
      tags:
      - Tweets
      summary: Returns Tweet objects liked by the provided User ID
      description: Returns a list of Tweets liked by the provided User ID
      operationId: usersIdLikedTweets
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - like.read
  /2/tweets/{id}/liking_users:
    get:
      tags:
      - Users
      summary: Returns user objects that have liked the provided Tweet ID
      description: Returns a list of users that have liked the provided Tweet ID
      operationId: tweetsIdLikingUsers
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - like.read
  /2/tweets/{id}/retweeted_by:
    get:
      tags:
      - Users
      summary: Returns user objects that have retweeted the provided Tweet ID
      description: Returns a list of users that have retweeted the provided Tweet
        ID
      operationId: tweetsIdRetweetingUsers
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
  /2/users/{id}/retweets:
    post:
      tags:
      - Tweets
      summary: Causes the user (in the path) to retweet the specified tweet
      description: Causes the user (in the path) to retweet the specified tweet. The
        user in the path must match the user context authorizing the request.
      operationId: usersIdRetweets
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - tweet.write
  /2/users/{id}/retweets/{source_tweet_id}:
    delete:
      tags:
      - Tweets
      summary: Causes the user (in the path) to unretweet the specified tweet
      description: Causes the user (in the path) to unretweet the specified tweet.
        The user must match the user context authorizing the request
      operationId: usersIdUnretweets
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - tweet.write
  /2/tweets/counts/recent:
    get:
      tags:
      - Tweets
      summary: Recent search counts
      description: Returns Tweet Counts from the last 7 days that match a search query.
      operationId: tweetCountsRecentSearch
      security:
      - BearerToken: []
  /2/tweets/counts/all:
    get:
      tags:
      - Tweets
      summary: Full archive search counts
      description: Returns Tweet Counts that match a search query.
      operationId: tweetCountsFullArchiveSearch
      security:
      - BearerToken: []
  /2/compliance/jobs:
    get:
      tags:
      - Compliance
      summary: List compliance jobs
      description: Returns recent compliance jobs for a given job type and optional
        job status
      operationId: listBatchComplianceJobs
      security:
      - BearerToken: []
    post:
      tags:
      - Compliance
      summary: Create compliance job
      description: Creates a compliance for the given job type
      operationId: createBatchComplianceJob
      security:
      - BearerToken: []
  /2/compliance/jobs/{id}:
    get:
      tags:
      - Compliance
      summary: Get compliance job
      description: Returns a single compliance job by ID
      operationId: getBatchComplianceJob
      security:
      - BearerToken: []
  /2/lists:
    post:
      tags:
      - Lists
      summary: Create List
      description: Creates a new List.
      operationId: listIdCreate
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
        - list.read
  /2/lists/{id}:
    get:
      tags:
      - Lists
      summary: List lookup by List ID
      description: Returns a List
      operationId: listIdGet
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
    put:
      tags:
      - Lists
      summary: Update List
      description: Update a List that you own.
      operationId: listIdUpdate
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
    delete:
      tags:
      - Lists
      summary: Delete List
      description: Delete a List that you own.
      operationId: listIdDelete
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/lists/{id}/followers:
    get:
      tags:
      - Users
      summary: Returns user objects that follow a List by the provided List ID
      description: Returns a list of users that follow a List by the provided List
        ID
      operationId: listGetFollowers
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
  /2/lists/{id}/members:
    get:
      tags:
      - Users
      summary: Returns user objects that are members of a List by the provided List
        ID
      description: Returns a list of users that are members of a List by the provided
        List ID
      operationId: listGetMembers
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
    post:
      tags:
      - Lists
      summary: Add a List member
      description: Causes a user to become a member of a List.
      operationId: listAddMember
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/lists/{id}/members/{user_id}:
    delete:
      tags:
      - Lists
      summary: Remove a List member
      description: Causes a user to be removed from the members of a List.
      operationId: listRemoveMember
      security:
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.write
  /2/lists/{id}/tweets:
    get:
      tags:
      - Tweets
      summary: List Tweets timeline by List ID
      description: Returns a list of Tweets associated with the provided List ID
      operationId: listsIdTweets
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - list.read
  /2/spaces/{id}:
    get:
      tags:
      - Spaces
      summary: Space lookup by Space ID
      description: Returns a variety of information about the Space specified by the
        requested ID
      operationId: findSpaceById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - space.read
  /2/spaces:
    get:
      tags:
      - Spaces
      summary: Space lookup up Space IDs
      description: Returns a variety of information about the Spaces specified by
        the requested IDs
      operationId: findSpacesByIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - space.read
  /2/spaces/by/creator_ids:
    get:
      tags:
      - Spaces
      summary: Space lookup by their creators
      description: Returns a variety of information about the Spaces created by the
        provided User IDs
      operationId: findSpacesByCreatorIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - space.read
  /2/spaces/search:
    get:
      tags:
      - Spaces
      summary: Search for Spaces
      description: Returns Spaces that match the provided query.
      operationId: searchSpaces
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - space.read
  /2/spaces/{id}/tweets:
    get:
      tags:
      - Spaces
      - Tweets
      summary: Retrieve tweets from a Space
      description: Retrieves tweets shared in the specified space
      operationId: spaceTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - space.read
  /2/spaces/{id}/buyers:
    get:
      tags:
      - Spaces
      - Tweets
      summary: Retrieve the list of users who purchased a ticket to the given space
      description: Retrieves the list of users who purchased a ticket to the given
        space
      operationId: spaceBuyers
      security:
      - BearerToken: []
      - UserToken: []
      - OAuth2UserToken:
        - users.read
        - tweet.read
        - space.read
components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
    UserToken:
      type: http
      scheme: OAuth
    OAuth2UserToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.twitter.com/2/oauth2/authorize
          tokenUrl: https://api.twitter.com/2/oauth2/token
          scopes:
            tweet.read: "Allows the app to view any Tweets the authenticated user\
              \ can see, including Tweets from protected accounts."
            tweet.write: Allows the app to tweet and retweet for the authenticated
              user.
            users.read: "Allows the app to view any account the authenticated user\
              \ can see, including protected accounts."
            list.write: Allows the app to create and manage lists for the authenticated
              user.
            list.read: "Allows the app to view any lists the authenticated user has\
              \ created and lists they are a member of, including private lists."
            like.read: Allows the app to read Tweets that the authenticated user has
              liked.
            like.write: Allows the app to like and un-likes Tweets for the authenticated
              user.
            mute.read: Allows the app to read the users the authenticated user has
              muted.
            mute.write: Allows the app to mute and unmute users for the authenticated
              user.
            block.read: Allows the app to read the users the authenticated user has
              blocked.
            block.write: Allows the app to block and unblock users for the authenticated
              user.
            tweet.moderate.write: Allows the app to hide and unhide replies to the
              authenticated user's Tweets.
            follows.read: Allows the app to read the users who follow the authenticated
              user and users that they follow.
            follows.write: Allows the app to follow and unfollow users for the authenticated
              user.
            space.read: Allows the app to read the Spaces the authenticated user can
              see.
            offline.access: Allows the app to request a refresh token.
            bookmark.read: Allows the app to read bookmarked Tweets
            bookmark.write: Allows the app to add/remove Tweets to/from bookmarks
